# Generated by Django 4.2.26 on 2026-04-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_teacher_user_users_single_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentEmailNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_enabled', models.BooleanField(default=True, verbose_name='E-mail: wiadomości')),
                ('payments_enabled', models.BooleanField(default=True, verbose_name='E-mail: płatności')),
                ('schedule_enabled', models.BooleanField(default=True, verbose_name='E-mail: plan zajęć')),
                ('closures_enabled', models.BooleanField(default=True, verbose_name='E-mail: dni wolne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Rodzic')),
            ],
            options={
                'verbose_name': 'Ustawienia e-mail powiadomień rodzica',
                'verbose_name_plural': 'Ustawienia e-mail powiadomień rodziców',
            },
        ),
        migrations.CreateModel(
            name='ParentEmailNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('messages', 'Wiadomości'), ('payments', 'Płatności'), ('schedule', 'Plan zajęć'), ('closures', 'Dni wolne')], max_length=20, verbose_name='Typ zdarzenia')),
                ('last_sent_on', models.DateField(blank=True, null=True, verbose_name='Ostatni dzień wysyłki')),
                ('pending_count', models.PositiveIntegerField(default=0, verbose_name='Liczba oczekujących zdarzeń')),
                ('pending_send_at', models.DateTimeField(blank=True, null=True, verbose_name='Wyślij nie wcześniej niż')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification_states', to=settings.AUTH_USER_MODEL, verbose_name='Rodzic')),
            ],
            options={
                'verbose_name': 'Stan e-mail powiadomień rodzica',
                'verbose_name_plural': 'Stany e-mail powiadomień rodziców',
            },
        ),
        migrations.AddConstraint(
            model_name='parentemailnotificationstate',
            constraint=models.UniqueConstraint(fields=('user', 'event_type'), name='users_parent_email_notification_state_unique'),
        ),
        migrations.AddIndex(
            model_name='parentemailnotificationstate',
            index=models.Index(fields=['pending_send_at'], name='users_email_pending_at_idx'),
        ),
        migrations.AddIndex(
            model_name='parentemailnotificationstate',
            index=models.Index(fields=['event_type'], name='users_email_event_type_idx'),
        ),
    ]
