# Generated by Django 4.2.26 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_parent_email_notification_settings_and_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentemailnotificationsettings',
            name='gallery_enabled',
            field=models.BooleanField(default=True, verbose_name='E-mail: galeria'),
        ),
        migrations.AddField(
            model_name='parentemailnotificationsettings',
            name='posts_enabled',
            field=models.BooleanField(default=True, verbose_name='E-mail: posty'),
        ),
        migrations.RenameField(
            model_name='parentemailnotificationsettings',
            old_name='closures_enabled',
            new_name='calendar_enabled',
        ),
        migrations.AlterField(
            model_name='parentemailnotificationsettings',
            name='calendar_enabled',
            field=models.BooleanField(default=True, verbose_name='E-mail: kalendarz'),
        ),
    ]
