# Generated by Django 4.2.26 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_parent_email_notification_categories'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE users_parentemailnotificationstate SET event_type='calendar' WHERE event_type='closures';",
            reverse_sql="UPDATE users_parentemailnotificationstate SET event_type='closures' WHERE event_type='calendar';",
        ),
        migrations.AlterField(
            model_name='parentemailnotificationstate',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('posts', 'Posty'),
                    ('messages', 'Wiadomości'),
                    ('gallery', 'Galeria'),
                    ('payments', 'Płatności'),
                    ('schedule', 'Plan zajęć'),
                    ('calendar', 'Kalendarz'),
                ],
                max_length=20,
                verbose_name='Typ zdarzenia',
            ),
        ),
    ]
