# Generated by Django 4.2.26 on 2026-04-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_parentemailnotificationstate_event_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE users_parentemailnotificationstate SET event_type='calendar' WHERE event_type='closures';",
            reverse_sql="UPDATE users_parentemailnotificationstate SET event_type='closures' WHERE event_type='calendar';",
        ),
    ]
