# Generated by Django 4.2.26 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_migrate_closures_event_type_to_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentemailnotificationsettings',
            name='posts_enabled',
            field=models.BooleanField(default=False, verbose_name='E-mail: posty'),
        ),
        migrations.AlterField(
            model_name='parentemailnotificationsettings',
            name='gallery_enabled',
            field=models.BooleanField(default=False, verbose_name='E-mail: galeria'),
        ),
        migrations.AlterField(
            model_name='parentemailnotificationsettings',
            name='schedule_enabled',
            field=models.BooleanField(default=False, verbose_name='E-mail: plan zajęć'),
        ),
        migrations.AlterField(
            model_name='parentemailnotificationsettings',
            name='calendar_enabled',
            field=models.BooleanField(default=False, verbose_name='E-mail: kalendarz'),
        ),
    ]
