# Generated by Django 4.2.26 on 2025-11-26 19:11

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data nieobecności')),
                ('status', models.CharField(choices=[('nieobecny', 'Nieobecny (Zgłoszone)')], default='nieobecny', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zgłoszenia')),
            ],
            options={
                'verbose_name': 'Obecność',
                'verbose_name_plural': 'Obecności',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('date_of_birth', models.DateField(verbose_name='Data urodzenia')),
                ('medical_info', django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Alergie, uwagi zdrowotne', verbose_name='Informacje medyczne'))),
            ],
            options={
                'verbose_name': 'Dziecko',
                'verbose_name_plural': 'Dzieci',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa Grupy')),
                ('teachers_info', models.TextField(help_text='Imiona i nazwiska nauczycieli', verbose_name='Informacje o nauczycielach')),
            ],
            options={
                'verbose_name': 'Grupa',
                'verbose_name_plural': 'Grupy',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('content', models.TextField(blank=True, verbose_name='Treść')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data publikacji')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.group', verbose_name='Dla grupy (puste = dla wszystkich)')),
            ],
            options={
                'verbose_name': 'Wpis/Aktualność',
                'verbose_name_plural': 'Tablica Aktualności',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('description', models.CharField(max_length=200, verbose_name='Opis')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Opłacone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('payment_title', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Tytuł płatności (generowany automatycznie/ zostawić pusty)')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='Dziecko')),
            ],
            options={
                'verbose_name': 'Płatność',
                'verbose_name_plural': 'Płatności',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.group', verbose_name='Grupa'),
        ),
    ]
