# Generated by Django 4.2.26 on 2025-11-26 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(related_name='child', to=settings.AUTH_USER_MODEL, verbose_name='Konto Rodzica'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.child', verbose_name='Dziecko'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('child', 'date')},
        ),
    ]
