# Generated by Django 4.2.26 on 2025-11-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data zamknięcia')),
                ('reason', models.CharField(blank=True, help_text='np. Przerwa świąteczna', max_length=200, verbose_name='Powód')),
            ],
            options={
                'verbose_name': 'Dzień wolny',
                'verbose_name_plural': 'Dni wolne od zajęć',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SpecialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa zajęć')),
                ('description', models.TextField(blank=True, verbose_name='Opis/Szczegóły')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Godzina rozpoczęcia')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Godzina zakończenia')),
                ('groups', models.ManyToManyField(related_name='special_activities', to='core.group', verbose_name='Dla grup')),
            ],
            options={
                'verbose_name': 'Zajęcia dodatkowe/Wycieczka',
                'verbose_name_plural': 'Plan zajęć (Niestandardowe)',
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
