# Generated by Django 4.2.26 on 2025-11-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facilityclosure_specialactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('breakfast', models.TextField(blank=True, verbose_name='Śniadanie')),
                ('lunch_soup', models.CharField(blank=True, max_length=200, null=True, verbose_name='Obiad: Zupa')),
                ('lunch_main_course', models.TextField(blank=True, null=True, verbose_name='Obiad: Drugie danie')),
                ('lunch_beverage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Obiad: Napój')),
                ('lunch_fruit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Obiad: Owoc/Deser')),
                ('fruit_break', models.TextField(blank=True, verbose_name='Przerwa na owoce / Podwieczorek')),
                ('allergens', models.CharField(blank=True, help_text='np. 1, 3, 7', max_length=200, verbose_name='Alergeny (numery)')),
            ],
            options={
                'verbose_name': 'Jadłospis dzienny',
                'verbose_name_plural': 'Jadłospis',
                'ordering': ['-date'],
            },
        ),
    ]
