# Generated by Django 4.2.26 on 2025-11-24 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_attendance_options_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Obecność', 'verbose_name_plural': 'Obecności'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Dziecko', 'verbose_name_plural': 'Dzieci'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupa', 'verbose_name_plural': 'Grupy'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Płatność', 'verbose_name_plural': 'Płatności'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.child', verbose_name='Dziecko'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('nieobecny', 'Nieobecny (Zgłoszone)')], default='nieobecny', max_length=10),
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.group', verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='child',
            name='medical_info',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Alergie, uwagi zdrowotne', verbose_name='Informacje medyczne')),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL, verbose_name='Konto Rodzica'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa Grupy'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teachers_info',
            field=models.TextField(help_text='Imiona i nazwiska nauczycieli', verbose_name='Informacje o nauczycielach'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='Dziecko'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Opłacone'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_title',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Tytuł płatności (generowany automatycznie/ zostawić pusty)'),
        ),
    ]
