# Generated by Django 4.2.26 on 2025-11-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailymenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='breakfast',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='breakfast_beverage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Napój'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='breakfast_fruit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Owoc / Dodatek'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='breakfast_main_course',
            field=models.TextField(blank=True, null=True, verbose_name='Drugie danie / Kanapki'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='breakfast_soup',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Zupa / Zupa mleczna'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='fruit_break',
            field=models.TextField(blank=True, verbose_name='Podwieczorek / Owoce'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='lunch_beverage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Napój'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='lunch_fruit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Owoc / Deser'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='lunch_main_course',
            field=models.TextField(blank=True, null=True, verbose_name='Drugie danie'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='lunch_soup',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Zupa'),
        ),
    ]
