# Generated by Django 4.2.26 on 2025-11-26 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_attendance_options_alter_child_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent_account',
        ),
        migrations.AddField(
            model_name='child',
            name='parent_account',
            field=models.ManyToManyField(related_name='child', to=settings.AUTH_USER_MODEL, verbose_name='Konto Rodzica'),
        ),
    ]
