# Generated by Django 4.2.26 on 2025-11-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_dailymenu_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialactivity',
            options={'ordering': ['-date', 'start_time'], 'verbose_name': 'Zajęcia dodatkowe/Wycieczka', 'verbose_name_plural': 'Plan zajęć'},
        ),
    ]
