# Generated by Django 4.2.26 on 2025-11-26 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_child_parent_account_child_parent_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent_account',
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(related_name='child', to=settings.AUTH_USER_MODEL, verbose_name='Konto Rodzica'),
        ),
    ]
