# Generated by Django 4.2.26 on 2025-12-01 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_likes_postcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('description', models.CharField(max_length=200, verbose_name='Opis (np. Czesne)')),
                ('frequency', models.CharField(choices=[('weekly', 'Co tydzień'), ('monthly', 'Co miesiąc'), ('yearly', 'Co rok')], default='monthly', max_length=10, verbose_name='Częstotliwość')),
                ('next_payment_date', models.DateField(verbose_name='Data następnej płatności')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to='core.child', verbose_name='Dziecko')),
            ],
            options={
                'verbose_name': 'Płatność Cykliczna (Szablon)',
                'verbose_name_plural': 'Płatności Cykliczne',
            },
        ),
    ]
