# Generated by Django 4.2.26 on 2025-12-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recurringpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data opłacenia'),
        ),
    ]
