# Generated by Django 4.2.26 on 2025-12-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł albumu')),
                ('description', models.TextField(blank=True, verbose_name='Opis wydarzenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='core.group', verbose_name='Dla grupy (puste = dla wszystkich)')),
            ],
            options={
                'verbose_name': 'Album Zdjęć',
                'verbose_name_plural': 'Galeria Zdjęć',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_albums/%Y/%m/', verbose_name='Zdjęcie')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Podpis (opcjonalnie)')),
                ('gallery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.galleryitem')),
            ],
        ),
    ]
