# Generated by Django 4.2.26 on 2025-12-10 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_galleryitem_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_galleries', to=settings.AUTH_USER_MODEL),
        ),
    ]
