# Generated by Django 4.2.26 on 2025-12-14 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_postcomment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_gallery_items', to=settings.AUTH_USER_MODEL, verbose_name='Autor (dyrektor)'),
        ),
    ]
