# Generated by Django 4.2.26 on 2026-02-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_galleryitem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='meal_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Stawka żywieniowa'),
        ),
    ]
