# Generated by Django 4.2.26 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_dailymenu_week_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preschool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time_from', models.TimeField(verbose_name='Godzina otwarcia (od)')),
                ('opening_time_to', models.TimeField(verbose_name='Godzina zamknięcia (do)')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Numer telefonu')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres email')),
                ('street', models.CharField(max_length=128, verbose_name='Ulica')),
                ('postal_code', models.CharField(max_length=16, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=64, verbose_name='Miejscowość')),
                ('bank_account_number', models.CharField(max_length=64, verbose_name='Numer konta bankowego')),
                ('directors', models.JSONField(verbose_name='Imiona i nazwiska dyrekcji (lista)')),
            ],
            options={
                'verbose_name': 'Przedszkole',
                'verbose_name_plural': 'Przedszkola',
            },
        ),
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'ordering': ['-week_start_date'], 'verbose_name': 'Jadłospis (zdjęcie)', 'verbose_name_plural': 'Jadłospis'},
        ),
    ]
