# Generated by Django 4.2.26 on 2026-03-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_preschool_alter_dailymenu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preschool',
            options={'verbose_name': 'Dane przedszkola', 'verbose_name_plural': 'Dane przedszkola'},
        ),
    ]
