# Generated by Django 4.2.26 on 2026-03-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_preschool_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='preschool',
            name='bank_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nazwa banku'),
        ),
    ]
