# Generated by Django 4.2.26 on 2025-11-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_message_options_alter_message_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wiadomość', 'verbose_name_plural': 'Wiadomości'},
        ),
    ]
